### ISSUE TITLE
Forms Sizing need to avoid scroll bars when not called for

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2892]
Good case in point is encounter tabs. i.e
![image](https://user-images.githubusercontent.com/1859985/72689199-fe300f00-3adc-11ea-826b-140ad8083735.png)
Inner scroll is unnecessary. This will cause problems for touch devices unless prevented with purpose.
This is one of the reason which i've spoken for our top patient info bar being a known height. Speaking off, there is still a lot of real estate in that top bar. I still say if somebody doesn't want condensed then all other areas of app can be full but top bar is always a known height (condensed)
This is how it should be:
![image](https://user-images.githubusercontent.com/1859985/72689344-66332500-3ade-11ea-9e0a-cd209b797ef5.png)

Guessing everybody is thrilled i'm sort of back! This may seem trivial but I promise it's not...

**Comment by bradymiller** [comment]
I am thrilled you are back!!!

**Comment by tywrenn** [comment]
This should be an issue that my BS4 branch addresses since I've been working with tab/height structure in it. We should be converting to a more uniform modal structure as well (some are the old structure and some are using BS4 modals which looks odd).

**Comment by Devvyky** [comment]
@sjpadgett how do I recreate this same issue?

**Comment by tywrenn** [comment]
@Devvyky This can be recreated in a few ways:

1. If you are on a mobile device and a page gets cut off for no reason (e.g. calendar)
2. On certain pages if you are trying to resize them the scrollbar messes up

Also we should not have a scrollbar on certain modals that we are using (e.g. adding a new event to the calendar). I'm not sure how to fix modals though (they are really tough to fix).

**Comment by stu01509** [comment]
Hello @bradymiller @tywrenn and @sjpadgett 

Is now the problem solved or anyone is working on this issue?
If not, I will try to fix it, Please assign this issue to me.

**Comment by bradymiller** [comment]
I am willing to be this issue was resolved with all the prior bs4 changes. Recommend testing it, though, to confirm.

**Comment by stu01509** [comment]
@bradymiller Thanks for your notice, I will take a look 😃

**Comment by stu01509** [comment]
Hello @bradymiller  @tywrenn and @sjpadgett 

I  reproduce the issue on Chrome, Seems like it didn't fix. Do you have any idea or suggestion for me to solve it?

![image](https://user-images.githubusercontent.com/22230889/78996318-ebc2f000-7b76-11ea-8e9d-6de5fd4a9b47.png)

**Comment by sjpadgett** [comment]
Just revert and leave alone please.

**Comment by bradymiller** [comment]
hi @sjpadgett , Is there no solution for this issue then?
(looks like we made the change on the wrong script here)

**Comment by sjpadgett** [comment]
It is fixed in encounter. You never should need to add overflow style to html tags but where container is created. You'll never get dynamic viewport sizing consistent across all browsers and devices imo. I learned this from auto sizing dialog.
Retest encounter as I put a fix in awhile back. Same fix I used since 501...

**Comment by stu01509** [comment]
Hi @bradymiller and @sjpadgett 

Should I continue to solve this issue?

**Comment by sjpadgett** [comment]
@stu01509 I fixed this I believe.
First the issue was with the tab summary container scroll not inner scroll. The fix is in the Tabs Summary when container is created.
![image](https://user-images.githubusercontent.com/1859985/80915427-4091fa80-8d20-11ea-885e-d3e569c294f5.png)

![image](https://user-images.githubusercontent.com/1859985/80915460-8058e200-8d20-11ea-8daf-14f7ef102bd5.png)

I'll close this issue but feel free to try different solution if ya want but, i'm keeping an eye on this and will test more as I go.
Thanks
