### ISSUE TITLE
Font-awesome icons are missing

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#3213]
### Describe the bug
Some of the font-awesome icons are not rendered. Shows `error 404 Not found`.
Refresh icon is not visible both in chrome and edge.

### Actual Behaviour
See for the icons search and refresh
![Screenshot (92)](https://user-images.githubusercontent.com/55142272/77252747-fc6cfe00-6c7b-11ea-9e2d-b6847734f3dd.png)

![Screenshot (94)](https://user-images.githubusercontent.com/55142272/77253083-38a15e00-6c7e-11ea-8233-6355fe6c1fcc.png)

- Browser: Chrome

**Comment by stephenwaite** [comment]
hi @adad20 , wasn't this fixed in most recent commit, https://github.com/openemr/openemr/commit/bc644eb4a1e54a27547ba066bc1065f005312d53 ?

**Comment by adad20** [comment]
hi @stephenwaite My repo is up to date and contains this commit yet this issue persists

**Comment by stu01509** [comment]
Hi @adad20 

Try to use, It will install font awesome 5

```npm install```

**Comment by adad20** [comment]
@stu01509  After pulling the latest commits I ran npm install yet some icons are missing like `refresh` one.

**Comment by bradymiller** [comment]
hi @adad20 , @stu01509 , and @stephenwaite , There are still broken icons out there including this one. In this case, `fa-refresh`no longer exists in fontawesome 5, and should be changed to `fa-sync`. Rec searching for `fa-refresh` in codebase to see where need to change (there look to be about 13 places).

**Comment by stu01509** [comment]
Hi @adad20 @bradymiller @stephenwaite 

I am in my environment just found refresh icon broken, it still used fa-refresh, Maybe I am not fully updated font awesome icon, So I create a PR to fix it.
