### ISSUE TITLE
setup.php error when supply a complex password for new openemr db user account

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3350]
In setup.php's "Step 2 - Database and OpenEMR Initial User Setup Details", if you supply a complex password for when setting up the openemr db user, then when moving forward to the next step it fails with "ERROR - A database login password is required". A simple password does not generate this error.

An example complex password is:
cn162`+wn|vCGjdS#^+vd;Uk9q%D+O?u

OpenEMR version : 5.0.2.1
Operating system: Debian 10

**Comment by stu01509** [comment]
Hello @pete-boyd and @bradymiller 

I try to reproduce it, But it seems normal in v5.0.3-dev
Maybe we fixed this issue in v5.0.3-dev?

![image](https://user-images.githubusercontent.com/22230889/79167520-28fadc80-7e1a-11ea-96eb-4c485c7cfaa5.png)

**Comment by pete-boyd** [comment]
I am still seeing this issue in 6.1.0. The password I used included the characters >+*-+}

**Comment by bradymiller** [comment]
Since this is stored in sites/default/sqlconf.php it appears that it is run through the following function to ensure no bad stuff is brought into that script, so the following characters are then considered illegal. We should make that clear in that password field.
https://github.com/openemr/openemr/blob/master/library/classes/Installer.class.php#L95
